blank_issues_enabled: false
contact_links: 
  - name: Discord Server
    about: 'Q & A'
    url: 'https://valapi.github.io/link/discord'
  - name: 'Guide'
    about: 'How to use'
    url: 'https://valapi.github.io'